Repository s2kdesign-com/CoinGarden-World-Full, pull requests merged in 2022-09, with the labels that each got.

#19 Coin Garden - Pages
  .vscode/launch.json
  .vscode/tasks.json
  src/landing-page/CoinGardenWorld.Web/Pages/Index.razor
  src/landing-page/CoinGardenWorld.Web/Pages/about-us/AboutUs.razor
  src/landing-page/CoinGardenWorld.Web/Pages/about/About.razor
  src/landing-page/CoinGardenWorld.Web/Pages/admin-intro/AdminInitro.razor
  src/landing-page/CoinGardenWorld.Web/Pages/app-download/AppDownload.razor
  src/landing-page/CoinGardenWorld.Web/Pages/charities/Charities.razor
  src/landing-page/CoinGardenWorld.Web/Pages/contact/Contact.razor
  src/landing-page/CoinGardenWorld.Web/Pages/documents/Documents.razor
  src/landing-page/CoinGardenWorld.Web/Pages/faq/Faq.razor
  src/landing-page/CoinGardenWorld.Web/Pages/features/Features.razor
  src/landing-page/CoinGardenWorld.Web/Pages/mobile-app/MobileApp.razor
  src/landing-page/CoinGardenWorld.Web/Pages/nft-market/NftMarket.razor
  src/landing-page/CoinGardenWorld.Web/Pages/problem/Problem.razor
  src/landing-page/CoinGardenWorld.Web/Pages/products/Products.razor
  src/landing-page/CoinGardenWorld.Web/Pages/roadmap/Roadmap.razor
  src/landing-page/CoinGardenWorld.Web/Pages/solution/Solution.razor
  src/landing-page/CoinGardenWorld.Web/Pages/team/Team.razor
  src/landing-page/CoinGardenWorld.Web/Pages/token/Token.razor
  src/landing-page/CoinGardenWorld.Web/Pages/tokensale/Tokensale.razor
  src/landing-page/CoinGardenWorld.Web/Pages/wallet/Wallet.razor
  src/landing-page/CoinGardenWorld.Web/Shared/Footer.razor
  src/landing-page/CoinGardenWorld.Web/Shared/Header.razor
  src/landing-page/CoinGardenWorld.Web/Shared/MainLayout.razor
  src/landing-page/CoinGardenWorld.Web/Shared/MainMenu.razor
  src/landing-page/CoinGardenWorld.Web/Shared/Modal.razor
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/bootstrap/bootstrap.min.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/bootstrap/bootstrap.min.css.map
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/rtl.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/style-azalea.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/style-azure.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/style-dark.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/style-jasmine.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/style-lavender.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/style-lungwort.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/style-muscari.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/style-salvia.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/style-zinnia.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/style.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/vendor.bundle.bs4.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/vendor.bundle.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/index.html
Labels: enhancement

#21 #2 Added .net 7 izolated Azure function for backend API for the nft store
  .github/workflows/azure-static-web-apps-lively-water-04019cd10.yml
  README.md
  src/CoinGardenWorld.Full.sln
  src/back-end/CoinGardenWorld.Store.AzureFunctionApi/.gitignore
  src/back-end/CoinGardenWorld.Store.AzureFunctionApi/.vscode/extensions.json
  src/back-end/CoinGardenWorld.Store.AzureFunctionApi/CoinGardenWorld.Store.AzureFunctionApi.csproj
  src/back-end/CoinGardenWorld.Store.AzureFunctionApi/Dockerfile
  src/back-end/CoinGardenWorld.Store.AzureFunctionApi/Program.cs
  src/back-end/CoinGardenWorld.Store.AzureFunctionApi/Properties/launchSettings.json
  src/back-end/CoinGardenWorld.Store.AzureFunctionApi/TestFunc.cs
  src/back-end/CoinGardenWorld.Store.AzureFunctionApi/host.json
Labels: enhancement, Back End

#25 change theme
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  src/landing-page/CoinGardenWorld.Web/AppState.cs
  src/landing-page/CoinGardenWorld.Web/Pages/Index.razor
  src/landing-page/CoinGardenWorld.Web/Pages/about-us/AboutUs.razor
  src/landing-page/CoinGardenWorld.Web/Pages/charities/Charities.razor
  src/landing-page/CoinGardenWorld.Web/Pages/contact/Contact.razor
  src/landing-page/CoinGardenWorld.Web/Pages/mobile-app/MobileApp.razor
  src/landing-page/CoinGardenWorld.Web/Pages/nft-market/NftMarket.razor
  src/landing-page/CoinGardenWorld.Web/Pages/token/Token.razor
  src/landing-page/CoinGardenWorld.Web/Program.cs
  src/landing-page/CoinGardenWorld.Web/Shared/Footer.razor
  src/landing-page/CoinGardenWorld.Web/Shared/MainLayout.razor
  src/landing-page/CoinGardenWorld.Web/Shared/ThemePageLoader.razor
  src/landing-page/CoinGardenWorld.Web/Shared/ThemeScriptLoader.razor
  src/landing-page/CoinGardenWorld.Web/ThemeJsInterop.cs
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/style-lobelia.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/css/theme.css
  src/landing-page/CoinGardenWorld.Web/wwwroot/assets/js/CoinGardenWorld.Web.lib.module.js
  src/landing-page/CoinGardenWorld.Web/wwwroot/index.html
  src/landing-page/CoinGardenWorld.Web/wwwroot/js/scripts.js
  src/landing-page/CoinGardenWorld.Web/wwwroot/themeJsInterop.js
Labels: enhancement

#27 fix main menu
  src/landing-page/CoinGardenWorld.Web/Pages/Index.razor
  src/landing-page/CoinGardenWorld.Web/Pages/about-us/AboutUs.razor
  src/landing-page/CoinGardenWorld.Web/Pages/charities/Charities.razor
  src/landing-page/CoinGardenWorld.Web/Pages/contact/Contact.razor
  src/landing-page/CoinGardenWorld.Web/Pages/mobile-app/MobileApp.razor
  src/landing-page/CoinGardenWorld.Web/Pages/nft-market/NftMarket.razor
  src/landing-page/CoinGardenWorld.Web/Pages/token/Token.razor
  src/landing-page/CoinGardenWorld.Web/Shared/Footer.razor
  src/landing-page/CoinGardenWorld.Web/Shared/HomeBanner.razor
  src/landing-page/CoinGardenWorld.Web/Shared/MainLayout.razor
  src/landing-page/CoinGardenWorld.Web/Shared/MainMenu.razor
  src/landing-page/CoinGardenWorld.Web/Shared/PagesBannerContainer.razor
Labels: bug
